# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CforGood' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CforGood
    pod ‘Branch’
 
  target 'CforGoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
