# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CforGood' do
  pod 'Stripe', '~> 10.1.0'
  
  # pod 'Branch-SDK', path: "../node_modules/react-native-branch/ios"
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CforGood
 
  target 'CforGoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
